### ISSUE TITLE
Local only support bugs

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-app#1091]
Bug1
Save popup should not open in the local support.

Bug2
Save changes popup and red dot for the API's should not appear.

bug3
Quick help guide button not working in collection.

bug4
See all shortcuts button not visible 

bug5
select environment and my workspace should be disabled.

bug6
With every new API request, help text is opening by default.

**Comment by Astitva877** [comment]
@shreyas070707  the save popup is fixed in new build cna you please check, and the red dot will come to show that data is unsaved add to  use that feature you have to login, we will provide workspace and environment in next phase that's why they are not disabled. Regarding the help text it is same as when we login. 

CC: @ayushadhikari93 @sanilnayak

**Comment by shreyas070707** [comment]
save pop up is not opening in local support when we click on save button


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/5bb6ee9e-ff47-4cf5-b422-06d953796830)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for mac

this pop up is present in windows


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/017bbe09-9b1c-46eb-ae47-64a2d2d9cecd)

**Comment by sanilnayak** [comment]
Not resolved all the bugs so moving this story to development we can take later.

**Comment by Astitva877** [comment]
@sanilnayak we don't have quick help button now and my workspace and environment will be enabled as discussed. fixed that see all shortcuts issue 
CC: @shreyas070707

**Comment by shreyas070707** [comment]
@Astitva877  please give tooltip in this save button


![Image](https://github.com/sparrowapp-dev/sparrow-app/assets/158440936/65bd9dfc-25dd-4b88-9a1a-b480ee7e57dc)

**Comment by shreyas070707** [comment]
@sanilnayak  please check for Mac

**Comment by sanilnayak** [comment]
@shreyas070707 
@Astitva877 and I had a discussion that this save popup will be there.
