### ISSUE TITLE
Rest API Tool issues 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1684]
- [x] User is not getting the response for infinite time when hitting any API then changed the tab and coming back to same API
- [x] If there is a debugger in the code, then user is not getting the response and after 60 sec its stopped.
- [x] When headers has huge count it is taking time to show up, its valid for API and WebSocket

**Comment by Astitva877** [comment]
@sanilnayak  these was fixed in previous sprint.

**Comment by sanilnayak** [comment]
### **Working in Mac:**

https://github.com/user-attachments/assets/f75b26ae-8054-4376-8a38-a79d6daa78f1

https://github.com/user-attachments/assets/e7069f17-b535-4fc0-8e75-32f013f4cb1d

**Comment by shreyas070707** [comment]
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/EQb38QC2GFVFqj7UDRmLYlQBLjSv-ZfzzIP3dosUVBuZ_g?e=0al422
working in windows and
When headers has huge count it is taking time to show up, its valid for API and WebSocket is happens when count is hugs, tested same in p-bot having same issue

**Comment by shreyas070707** [comment]
@Astitva877 Please check the loading issue is still there in windows(tested with 100 headers)
In bulk edit, user need to click on screen to see the last headers
https://github.com/user-attachments/assets/5119d972-fe9c-46ef-b99c-ad4c02d6ddc7

**Comment by itsmdasifraza** [comment]
Its working fine on windows. could you please share screen recording for better reference. @shreyas070707 @sanilnayak

**Comment by Astitva877** [comment]
@shreyas070707 the headers are getting loaded till 100 correctly, can you please re-check.

**Comment by shreyas070707** [comment]
headers till 100 are working as expected

https://github.com/user-attachments/assets/fac04ec3-feeb-4987-99d4-03fb782fbb6f
