### ISSUE TITLE
Left Panel Revamped

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app#1703]
- [x] While searching any text which is not available in Collection/Environment/Testflow then placeholder is not appearing as figma.

- [x] While searching any text Collection/Environment dropdown is opening and showing the search result but test flow is not showing

- [x] Place holder in collection while there is zero collection count, placeholder is not matching with figma colour and dyanamics

- [x] 3 dots and "+" button's dropdown in collection/folder are not as per figma

**Comment by Abhishek9503** [comment]
The first bug that you have listed in this list is that , the no result found state that mentioned in figma , at the time of development we have not taken that desgin we have implemented the desgin which is currently in development , the desgin that is in development is not updated by figma team.

CC :- @Monika-APM  @sanilnayak

**Comment by Abhishek9503** [comment]
We have changed + button data but it is not updated on Figma  and also we are not taking the New word in any of the section for creating any new thing .

CC; :- @shreyas070707 @sanilnayak  @Monika-APM

**Comment by Abhishek9503** [comment]
We have taken the three dot icon as horizontal so  we will make them as  acc to figma in the next PR of mine .

CC :- @Monika-APM  @shreyas070707

**Comment by shreyas070707** [comment]
[ ] 3 dots and "+" button's dropdown in collection/folder are not as per figma(Not Solved)

![Image](https://github.com/user-attachments/assets/3eca22b6-fc0e-4160-85b3-64afe85479e4)
**Bug**
"+" button present in the collection is still not according to figma(3 dots is not according to figma)
Expected-
![Image](https://github.com/user-attachments/assets/a081e1cb-4e55-4571-b80a-2a8aae35daca)
Actual-
![Image](https://github.com/user-attachments/assets/7b1cd6b1-e0f8-4342-9fb1-79c338784c3b)

- [ ] Place holder in collection while there is zero collection count, placeholder is not matching with figma colour and dynamics(Solved)
![Image](https://github.com/user-attachments/assets/1e9cbe80-c46b-4915-b407-a097ab55a8ae)

- [ ] 
While searching any text Collection/Environment dropdown is opening and showing the search result but test flow is not showing(Solved)
![Image](https://github.com/user-attachments/assets/601b411f-e448-4ffb-b41d-ca1757595655)

- [ ] While searching any text which is not available in Collection/Environment/Testflow then placeholder is not appearing as figma.(Solved)
![Image](https://github.com/user-attachments/assets/b445879b-01a8-43aa-acae-b34140f39b0f)

**Comment by sanilnayak** [comment]
- [ ] 3 dots and "+" button's dropdown in collection/folder are not as per figma(Not Solved)


    ![Image](https://github.com/user-attachments/assets/c810b3a1-ee01-4c03-b648-5e9b3fffb5ed)


- [ ] "+" button present in the collection is still not according to figma(3 dots is not according to figma)
Expected-

   ![Image](https://github.com/user-attachments/assets/a28a25fe-65dd-4699-a53c-6f0f0417e9b3)


Actual- 


   ![Image](https://github.com/user-attachments/assets/c0099cbf-6d16-471d-bd8d-f6e7811d1231)


- [ ] Place holder in collection while there is zero collection count, placeholder is not matching with figma colour and dynamics(Solved)

    ![Image](https://github.com/user-attachments/assets/18c5dc06-c8e0-4016-86d9-c3f2bf5b3fa4)


- [ ] While searching any text Collection/Environment dropdown is opening and showing the search result but test flow is not showing(Solved)
         
    ![Image](https://github.com/user-attachments/assets/69c965b8-55b8-41fb-9ee3-61217e6e1f3a)


- [ ] While searching any text which is not available in Collection/Environment/Testflow then placeholder is not appearing as figma.(Solved)

    ![Image](https://github.com/user-attachments/assets/8fb0fe39-b27c-4c9e-9eef-8bb8b00bc080)

**Comment by shreyas070707** [comment]
While searching any text which is not available in Collection/Environment/Testflow then placeholder is not appearing as figma.-Solved
![image](https://github.com/user-attachments/assets/70fa44a0-cb97-4ee2-ab52-073cc9f2bf9f)


 While searching any text Collection/Environment dropdown is opening and showing the search result but test flow is not showing
![image](https://github.com/user-attachments/assets/392fe954-84a4-4e2a-840e-45f9ffbbd686)


 Place holder in collection while there is zero collection count, placeholder is not matching with figma colour and dyanamics
![image](https://github.com/user-attachments/assets/17caf718-fcb0-42aa-8559-4bf9288fb762)

 3 dots and "+" button's dropdown in collection/folder are not as per figma-Not  confirmed with design
